[deps]
ArgParse = "c7e460c6-2fb9-53a9-8c5b-16f535851c63"
Dash = "1b08a953-4be3-4667-9a23-3db579824955"
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
PlotlyJS = "f0f68f2c-4968-5e81-91da-67840de0976a"
